// Schema and validation for the curated tide-relationship artifact
// (`data/tide_relationships.jsonc`, served as `/tide-relationships-data.json`),
// the second input the `tides` pool variant reads alongside the tide decks
// (`data/tides.jsonc`). Where the tide decks are baked from the decklist corpus
// and regenerated by `npm run bake-tides`, the relationships are curated data
// owned by a human: each tide's ordered allied tides (the decks that work well
// together), and each Dreamcaller's tide pool (the tides its lead is drawn
// from). A draft pool draws a lead tide from the Dreamcaller's pool and fills
// it with the lead's allies until the pool is full — every tide that joins is
// justified by one of these published relationships, never a uniform-random
// draw.
//
// Both ally ids and Dreamcaller tide-pool ids name tides in `data/tides.jsonc`.
// Because the relationships are curated against a specific set of baked tides,
// re-baking the tide decks (changing tide ids or contents) invalidates this
// file: it must be re-seeded and re-curated, and a dangling tide id here is a
// hard validation error so a stale combination cannot ship silently. Pure and
// dependency-free so the seed script, the experiment harnesses, the unit tests,
// and the browser loader all share one implementation.

/** The committed tide-relationship artifact (`data/tide_relationships.jsonc`). */
export interface TideRelationshipsJson {
  version: number;
  /**
   * Per tide id: its ordered allied-tide ids, best ally first. The runtime
   * fills a pool from this list (a pool uses 1-3). Every tide must have an
   * entry; a tide may have an empty ally list (the runtime then falls back to
   * its allies' allies, breadth-first). No tide may list itself.
   */
  alliesByTide: Record<string, string[]>;
  /**
   * Per Dreamcaller UUID: the tide pool its lead tide is drawn from. Every
   * Dreamcaller (signatured or neutral) has an entry; each entry names at least
   * one tide.
   */
  tidePoolByDreamcaller: Record<string, string[]>;
}

function fail(detail: string): never {
  throw new Error(`Tide-relationship artifact is malformed: ${detail}.`);
}

/**
 * Validate a parsed `/tide-relationships-data.json` payload against the set of
 * known tide ids and return it typed. Throws on any structural problem (missing
 * fields, an ally or tide-pool id that names no tide, a tide missing from
 * `alliesByTide`, a self-ally, an empty tide pool) so a bad or stale artifact
 * fails loudly at load time instead of producing a quietly wrong pool.
 *
 * @param json the parsed payload.
 * @param tideIds the set of tide ids from `data/tides.jsonc` every reference
 *   must name. Pass the ids of the tides this relationships file is paired with.
 */
export function validateTideRelationships(
  json: unknown,
  tideIds: ReadonlySet<string>,
): TideRelationshipsJson {
  if (typeof json !== "object" || json === null) fail("not an object");
  const data = json as Partial<TideRelationshipsJson>;
  if (typeof data.version !== "number") fail("missing numeric `version`");

  const allies = data.alliesByTide;
  if (typeof allies !== "object" || allies === null || Array.isArray(allies)) {
    fail("missing `alliesByTide` object");
  }
  // Every tide must carry an ally list, and no list may name a non-tide or
  // itself.
  for (const tideId of tideIds) {
    if (!Object.prototype.hasOwnProperty.call(allies, tideId)) {
      fail(`tide "${tideId}" is missing from alliesByTide`);
    }
  }
  for (const [tideId, list] of Object.entries(allies)) {
    if (!tideIds.has(tideId)) fail(`alliesByTide key "${tideId}" names no tide`);
    if (!Array.isArray(list)) fail(`allies for "${tideId}" is not an array`);
    for (const allyId of list) {
      if (typeof allyId !== "string" || !tideIds.has(allyId)) {
        fail(`ally "${String(allyId)}" of "${tideId}" names no tide`);
      }
      if (allyId === tideId) fail(`tide "${tideId}" lists itself as an ally`);
    }
  }

  const pools = data.tidePoolByDreamcaller;
  if (typeof pools !== "object" || pools === null || Array.isArray(pools)) {
    fail("missing `tidePoolByDreamcaller` object");
  }
  for (const [dreamcallerId, list] of Object.entries(pools)) {
    if (!Array.isArray(list) || list.length === 0) {
      fail(`tide pool for "${dreamcallerId}" is empty`);
    }
    for (const tideId of list) {
      if (typeof tideId !== "string" || !tideIds.has(tideId)) {
        fail(`tide-pool id "${String(tideId)}" for "${dreamcallerId}" names no tide`);
      }
    }
  }

  return data as TideRelationshipsJson;
}
