// Smoke test for the committed automation-candidate catalog
// (`docs/automation-audit.json`, generated by
// `scripts/audit-automation-candidates.mjs`).
//
// Bug class guarded: a malformed catalog silently breaks every downstream
// registration / coverage step (Tasks 5-9 key a registry off these entries).
// This test asserts the catalog is structurally sound — it does NOT assert
// specific card counts or names, so it survives card-pool churn.

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { describe, expect, it } from "vitest";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");

const ALLOWED_TRIGGERS = new Set(["dawn", "materialized", "support"]);
const ALLOWED_CLASSIFICATIONS = new Set([
  "deterministic",
  "interactive",
  "partial",
  "manual",
]);
const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

interface CatalogEntry {
  id: string;
  name: string;
  triggers: string[];
  ruleLines: Record<string, string>;
  effects: Array<{ kind: string }>;
  classification: string;
  scriptable: boolean;
  notes?: string;
}

function loadCatalog(): { generatedFrom: string; cards: CatalogEntry[] } {
  const raw = readFileSync(
    join(REPO_ROOT, "docs", "automation-audit.json"),
    "utf8"
  );
  return JSON.parse(raw) as { generatedFrom: string; cards: CatalogEntry[] };
}

function loadCardIds(): Set<string> {
  const raw = readFileSync(
    join(REPO_ROOT, "public", "cards_v2-data.json"),
    "utf8"
  );
  const cards = JSON.parse(raw) as Array<{ id: string }>;
  return new Set(cards.map((c) => c.id));
}

describe("automation-audit catalog", () => {
  it("parses and points at the expected source", () => {
    const catalog = loadCatalog();
    expect(catalog.generatedFrom).toBe("public/cards_v2-data.json");
    expect(Array.isArray(catalog.cards)).toBe(true);
    expect(catalog.cards.length).toBeGreaterThan(0);
  });

  it("has structurally valid entries consistent with the schema", () => {
    const catalog = loadCatalog();
    const cardIds = loadCardIds();

    for (const entry of catalog.cards) {
      // Valid UUID that exists in the card pool.
      expect(UUID_RE.test(entry.id), `bad uuid: ${entry.id}`).toBe(true);
      expect(cardIds.has(entry.id), `unknown card id: ${entry.id}`).toBe(true);

      // Non-empty triggers, only allowed values.
      expect(Array.isArray(entry.triggers)).toBe(true);
      expect(entry.triggers.length, `empty triggers: ${entry.id}`).toBeGreaterThan(0);
      for (const t of entry.triggers) {
        expect(ALLOWED_TRIGGERS.has(t), `bad trigger ${t} on ${entry.id}`).toBe(
          true
        );
      }

      // Each trigger has a corresponding rule line.
      for (const t of entry.triggers) {
        expect(
          typeof entry.ruleLines[t],
          `missing ruleLine for ${t} on ${entry.id}`
        ).toBe("string");
      }

      // Classification in the allowed set.
      expect(
        ALLOWED_CLASSIFICATIONS.has(entry.classification),
        `bad classification ${entry.classification} on ${entry.id}`
      ).toBe(true);

      // scriptable consistent with classification: manual => false, else true.
      if (entry.classification === "manual") {
        expect(entry.scriptable, `manual must be unscriptable: ${entry.id}`).toBe(
          false
        );
      } else {
        expect(
          entry.scriptable,
          `${entry.classification} must be scriptable: ${entry.id}`
        ).toBe(true);
      }

      // effects is always an array.
      expect(Array.isArray(entry.effects), `effects not array: ${entry.id}`).toBe(
        true
      );
    }
  });

  it("has unique ids sorted ascending (deterministic output)", () => {
    const catalog = loadCatalog();
    const ids = catalog.cards.map((c) => c.id);
    const sorted = [...ids].sort();
    expect(ids).toEqual(sorted);
    expect(new Set(ids).size).toBe(ids.length);
  });
});
