import type { CardSourceDebugState } from "../../types/quest";
import type { Idf3ProvenanceSummary, SeedProvenanceSummary, Tides4ProvenanceSummary } from "../../types/content";
import type { CardSourceView } from "../../cumulus/screens/CardSourceDialog";
import { seedProvenanceVariantCopy } from "../../draft/pool/seed-provenance-copy";

/** Maps computed provenance into display copy; it never mutates or recomputes the run pool. */
export function buildCardSourceView(debug: CardSourceDebugState | null, idf3: Idf3ProvenanceSummary | null, seed: SeedProvenanceSummary | null, tides: Tides4ProvenanceSummary | null): CardSourceView | null {
  if (debug === null) return null;
  const cards = debug.entries ?? [];
  if (tides !== null) return { title: debug.screenLabel, subtitle: `${surface(debug.surface)} dealt from your Dreamcaller's tides.`, construction: { id: "construction", title: "How this pool was built", lines: ["Signature tide", ...tides.tides.filter((tide) => tide.role === "signature").map((tide) => tide.displayName ?? tide.name), "Theme tides", `${String(tides.facetDrawnCount)} of ${String(tides.facetAvailableCount)} theme tides were drawn at random.`, "Deal", `Built to ${String(tides.dealSize)} cards at a ${String(tides.cap)}-copy cap.`] }, cards: { id: "cards", title: "The cards in front of you", lines: cards.map((entry) => tideLine(entry.cardNumber, entry.cardName, tides)) } };
  if (seed !== null) return { title: debug.screenLabel, subtitle: `${surface(debug.surface)} ${seedProvenanceVariantCopy(seed.variant).headerAffinityTail}.`, construction: { id: "construction", title: "How this pool was built", lines: ["Seed card", `${seed.seedCardName} was chosen uniformly at random.`, "Affinity", seed.variant === "pickfit" ? "The pool reflects what drafters took over what they passed." : "Cards grow by affinity around the seed.", "Growth", `${String(seed.targetSize)} target copies.`] }, cards: { id: "cards", title: "The cards in front of you", lines: cards.map((entry) => seedLine(entry.cardNumber, entry.cardName, seed)) } };
  if (idf3 !== null) return { title: debug.screenLabel, subtitle: `${surface(debug.surface)} from the Dreamcaller’s reconstructed pool.`, construction: { id: "construction", title: "How this pool was built", lines: ["Signature", ...idf3.signatureCardNames, "Anchor decks", ...idf3.anchors.map((anchor) => `${String(Math.round(anchor.similarityToSignature * 100))}% match to signature`), "Starter deck", `${String(idf3.starterCardCount)} cards`, "Growth"] }, cards: { id: "cards", title: "The cards in front of you", lines: cards.map((entry) => idfLine(entry.cardNumber, entry.cardName, idf3)) } };
  return { title: debug.screenLabel, subtitle: "Why am I seeing these cards?", construction: null, cards: { id: "cards", title: "The cards in front of you", lines: cards.map((entry) => entry.inStarterDecklist ? `${entry.cardName}: Starter deck. In your starter deck.` : `${entry.cardName}: Pool card. Draft-pool card. ${String(entry.draftPoolCopies ?? 0)} copies in the pool.`) } };
}
function surface(surface: CardSourceDebugState["surface"]): string { return surface === "Draft" ? "These draft cards come" : surface === "Shop" ? "Shop cards are drawn" : "Rewards are drawn"; }
function tideLine(number: number, name: string, provenance: Tides4ProvenanceSummary): string { const source = provenance.cardProvenanceByNumber[String(number)]; const tide = provenance.tides.find((value) => value.id === source?.primaryTideId); if (tide === undefined) return `${name}: Pool card.`; const label = tide.displayName ?? tide.name; return tide.role === "signature" ? `${name}: From your signature tide ${label}.` : tide.role === "facet" ? `${name}: From the theme tide ${label}, one of the ${String(provenance.facetDrawnCount)} drawn at random this run.` : `${name}: From the tide ${label}.`; }
function seedLine(number: number, name: string, provenance: SeedProvenanceSummary): string { const source = provenance.cardProvenanceByNumber[String(number)]; return source?.isSeed ? `${name}: The seed card.` : `${name}: ${String(source?.copies ?? 0)} copies; affinity to the pool ${String(Math.round((source?.poolAffinity ?? 0) * 100))}%.`; }
function idfLine(number: number, name: string, provenance: Idf3ProvenanceSummary): string { const source = provenance.cardProvenanceByNumber[String(number)]; return source?.inStarterDeck ? `${name}: In your starter deck.` : `${name}: From source deck ${String(source?.sourceRank ?? "unknown")} at ${String(Math.round((source?.sourceSimilarity ?? 0) * 100))}%; that deck features this card.`; }
