import type {
  TransfigurationData,
  TransfigurationFormDefinition,
} from "../types/transfiguration-data";
import type { TransfigurationType } from "../types/journey";

const FIXTURE: TransfigurationData = {
  schemaVersion: 1,
  contentHash: "a".repeat(64),
  foldHash: "b".repeat(64),
  site: {
    rulesVersion: "fixture-transfiguration-rules",
    standardChoiceLimit: 3,
    enhancedChoiceLimit: null,
    formOrder: [
      "Empowered",
      "Amplified",
      "Kindled",
      "Inspired",
      "Enduring",
      "Hastened",
      "Resonant",
      "Attuned",
      "Perfected",
    ],
    pricing: {
      minimumCost: 0,
      maximumCost: 100,
      step: 10,
      statDeltaBands: [
        { minimumDelta: 1, maximumDelta: 1, base: 10, jitter: 0, floor: 10 },
        { minimumDelta: 2, base: 30, jitter: 0, floor: 30 },
      ],
    },
  },
  forms: [
    {
      id: "Empowered",
      glossaryUuid: "00000000-0000-4000-8000-000000000001",
      name: "Fixture Empowered",
      effectDisclosure: "Fixture energy effect",
      selectedCardDescription: "Fixture selected energy effect",
      accessibilityDescription: "Fixture accessible energy effect",
      glyph: "transfigurationEmpowered",
      accentColor: "#111111",
      tintColor: "#aaaaaa",
      displayOrder: 0,
      merchantAllowed: true,
      eligibility: { kind: "positiveEnergyCost" },
      operation: { kind: "halveEnergyCost", rounding: "Down", minimum: 0 },
      pricing: { kind: "statDelta" },
      benefit: { kind: "ratio", divisor: 2 },
    },
    {
      id: "Amplified",
      glossaryUuid: "00000000-0000-4000-8000-000000000002",
      name: "Fixture Amplified",
      effectDisclosure: "Fixture amplified effect",
      selectedCardDescription: "Fixture selected amplified effect",
      accessibilityDescription: "Fixture accessible amplified effect",
      glyph: "transfigurationAmplified",
      accentColor: "#222222",
      tintColor: "#bbbbbb",
      displayOrder: 1,
      merchantAllowed: true,
      eligibility: { kind: "distinctAuthoredAmplifiedText" },
      operation: { kind: "useAuthoredAmplifiedText" },
      pricing: { kind: "band", base: 10, jitter: 0, floor: 10 },
      benefit: { kind: "flat", value: 0.4 },
    },
    {
      id: "Kindled",
      glossaryUuid: "00000000-0000-4000-8000-000000000003",
      name: "Fixture Kindled",
      effectDisclosure: "Fixture spark effect",
      selectedCardDescription: "Fixture selected spark effect",
      accessibilityDescription: "Fixture accessible spark effect",
      glyph: "transfigurationKindled",
      accentColor: "#333333",
      tintColor: "#cccccc",
      displayOrder: 2,
      merchantAllowed: true,
      eligibility: { kind: "cardType", cardType: "Character" },
      operation: { kind: "doubleSpark", zeroResult: 1 },
      pricing: { kind: "statDelta" },
      benefit: { kind: "ratio", divisor: 4 },
    },
    {
      id: "Inspired",
      glossaryUuid: "00000000-0000-4000-8000-000000000004",
      name: "Fixture Inspired",
      effectDisclosure: "Fixture draw effect",
      selectedCardDescription: "Fixture selected draw effect",
      accessibilityDescription: "Fixture accessible draw effect",
      glyph: "transfigurationInspired",
      accentColor: "#444444",
      tintColor: "#dddddd",
      displayOrder: 3,
      merchantAllowed: true,
      eligibility: { kind: "cardType", cardType: "Event" },
      operation: { kind: "appendRulesClause", clause: "DrawCard" },
      pricing: { kind: "band", base: 20, jitter: 0, floor: 20 },
      benefit: { kind: "flat", value: 0.5 },
    },
    {
      id: "Enduring",
      glossaryUuid: "00000000-0000-4000-8000-000000000005",
      name: "Fixture Enduring",
      effectDisclosure: "Fixture reclaim effect",
      selectedCardDescription: "Fixture selected reclaim effect",
      accessibilityDescription: "Fixture accessible reclaim effect",
      glyph: "transfigurationEnduring",
      accentColor: "#555555",
      tintColor: "#eeeeee",
      displayOrder: 4,
      merchantAllowed: true,
      eligibility: { kind: "cardType", cardType: "Event" },
      operation: { kind: "appendRulesClause", clause: "Reclaim" },
      pricing: { kind: "band", base: 30, jitter: 0, floor: 30 },
      benefit: { kind: "flat", value: 0.5 },
    },
    {
      id: "Hastened",
      glossaryUuid: "00000000-0000-4000-8000-000000000006",
      name: "Fixture Hastened",
      effectDisclosure: "Fixture fast effect",
      selectedCardDescription: "Fixture selected fast effect",
      accessibilityDescription: "Fixture accessible fast effect",
      glyph: "transfigurationHastened",
      accentColor: "#666666",
      tintColor: "#999999",
      displayOrder: 5,
      merchantAllowed: true,
      eligibility: { kind: "eventWithoutFast" },
      operation: { kind: "setFast" },
      pricing: { kind: "free" },
      benefit: { kind: "flat", value: 0.5 },
    },
    {
      id: "Resonant",
      glossaryUuid: "00000000-0000-4000-8000-000000000007",
      name: "Fixture Resonant",
      effectDisclosure: "Fixture trigger effect",
      selectedCardDescription: "Fixture selected trigger effect",
      accessibilityDescription: "Fixture accessible trigger effect",
      glyph: "transfigurationResonant",
      accentColor: "#777777",
      tintColor: "#888888",
      displayOrder: 6,
      merchantAllowed: true,
      eligibility: { kind: "namedTrigger" },
      operation: { kind: "widenNamedTrigger" },
      pricing: { kind: "band", base: 40, jitter: 0, floor: 40 },
      benefit: { kind: "flat", value: 0.5 },
    },
    {
      id: "Attuned",
      glossaryUuid: "00000000-0000-4000-8000-000000000008",
      name: "Fixture Attuned",
      effectDisclosure: "Fixture ability effect",
      selectedCardDescription: "Fixture selected ability effect",
      accessibilityDescription: "Fixture accessible ability effect",
      glyph: "transfigurationAttuned",
      accentColor: "#121212",
      tintColor: "#ababab",
      displayOrder: 7,
      merchantAllowed: true,
      eligibility: { kind: "activatedEnergyCost" },
      operation: { kind: "reduceActivatedEnergyCost", amount: 1, minimum: 0 },
      pricing: { kind: "band", base: 10, jitter: 0, floor: 10 },
      benefit: { kind: "flat", value: 0.5 },
    },
    {
      id: "Perfected",
      glossaryUuid: "00000000-0000-4000-8000-000000000009",
      name: "Fixture Perfected",
      effectDisclosure: "Fixture combined effect",
      selectedCardDescription: "Fixture selected combined effect",
      accessibilityDescription: "Fixture accessible combined effect",
      glyph: "transfigurationPerfected",
      accentColor: "#232323",
      tintColor: "#bcbcbc",
      displayOrder: 8,
      merchantAllowed: false,
      eligibility: { kind: "atLeastEligibleForms", count: 2 },
      operation: {
        kind: "applyEligibleForms",
        formOrder: [
          "Empowered",
          "Amplified",
          "Kindled",
          "Inspired",
          "Enduring",
          "Hastened",
          "Resonant",
          "Attuned",
        ],
      },
      pricing: { kind: "band", base: 100, jitter: 0, floor: 100 },
      benefit: { kind: "flat", value: 0.6 },
    },
  ],
};

export function transfigurationFixture(): TransfigurationData {
  return FIXTURE;
}

export function transfigurationFormFixture(
  id: TransfigurationType,
): TransfigurationFormDefinition {
  const form = FIXTURE.forms.find((candidate) => candidate.id === id);
  if (form === undefined)
    throw new Error(`Missing Transfiguration fixture ${id}`);
  return form;
}
