// Cross-checks two independently-maintained artifacts to catch the
// "registered some cards, forgot a batch" failure mode:
//
//   1. the committed automation catalog `docs/automation-audit.json`
//      (generated by `scripts/audit-automation-candidates.mjs`), and
//   2. the hand-written registry `BATTLE_CARD_EFFECTS`
//      (`battle-card-effects-table.ts`).
//
// This reads the COMMITTED snapshot of the catalog, not a live re-derivation
// from TOML / card data, so routine card-pool churn does NOT trip it. It only
// changes when the audit is deliberately re-run.
//
// Bug classes guarded:
//   - PRIMARY: an audited, `scriptable: true` card never got registered in
//     `BATTLE_CARD_EFFECTS` (a whole batch was forgotten).
//   - SECONDARY: a `scriptable: false` (manual) card was wrongly registered —
//     a card the audit deemed unscriptable must not have a script.

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { describe, expect, it } from "vitest";
import { BATTLE_CARD_EFFECTS } from "./battle-card-effects-table";
import { parseCardId, type CardId } from "../../types/card-identity";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");

interface CatalogEntry {
  id: CardId;
  scriptable: boolean;
}

function loadCatalog(): { cards: CatalogEntry[] } {
  const raw = readFileSync(
    join(REPO_ROOT, "docs", "automation-audit.json"),
    "utf8"
  );
  const parsed = JSON.parse(raw) as {
    cards: Array<Omit<CatalogEntry, "id"> & { id: unknown }>;
  };
  return {
    cards: parsed.cards.map((card) => ({
      ...card,
      id: parseCardId(card.id),
    })),
  };
}

describe("battle-card automation registry coverage", () => {
  it("registers every scriptable audited card", () => {
    const catalog = loadCatalog();
    const scriptable = catalog.cards.filter((c) => c.scriptable === true);
    const missing = scriptable
      .filter((c) => !(c.id in BATTLE_CARD_EFFECTS))
      .map((c) => c.id);

    expect(
      missing,
      `scriptable cards not registered in BATTLE_CARD_EFFECTS: ${missing.join(
        ", "
      )}`
    ).toEqual([]);
  });

  it("does not register any non-scriptable (manual) audited card", () => {
    const catalog = loadCatalog();
    const extra = catalog.cards
      .filter((c) => c.scriptable === false && c.id in BATTLE_CARD_EFFECTS)
      .map((c) => c.id);

    expect(
      extra,
      `non-scriptable (manual) cards wrongly registered in ` +
        `BATTLE_CARD_EFFECTS: ${extra.join(", ")}`
    ).toEqual([]);
  });
});
