// Bake the committed `tides5` artifact the `tides5` pool variant combines into
// draft pools.
//
//   node scripts/bake-tides5.mjs           # writes data/tides5.jsonc + docs/cards2/tides5_decklists.md
//   node scripts/bake-tides5.mjs --out /tmp/tides5.jsonc --doc /tmp/tides5.md
//
// `tides5` is the SAME algorithm as `tides4` — the human-legible counterpart of
// `sigseed`, baking the axes of its run-to-run variety as separate signature /
// facet / neutral tide decks and recombining a random few per run — applied to a
// DIFFERENT, curated corpus. Where `tides4` learns from every usable draft seat,
// `tides5` learns ONLY from the known-good decklists catalogued in
// `docs/known_good_decklists.json`: every other draft seat is discarded before the
// pick-affinity corpus is built. The known-good list is a hand-vetted set of real
// drafted decks (nonland mainboard ≤ 30, sideboard ≥ 6, sealed pools excluded),
// identified by `(draftId, seat)`. The bake keeps only those seats' pick records.
//
// Because the generator is shared verbatim with `tides4` (`buildTides4`), the only
// difference between the two artifacts is the data the corpus is grown from. The
// bake reuses the canonical draft-record reader (`buildDraftRecords`) so a seat
// that survives in both corpora is byte-identical to its `tides4` record; it
// relaxes only the "exactly 30 trimmed picks" rule, so the known-good seats drawn
// from non-standard drafts (5 packs of 9, a single oversized pack) — which the
// standard bundle drops — are kept too. Every known-good seat the source data can
// represent contributes its high-signal early picks.
//
// The bake is a pure function of the bundled cards + the known-good draft records +
// signatures (no randomness; sorted tie-breaks throughout): re-baking the same
// inputs yields a byte-identical body. Cards are keyed by their stable cards_v2
// UUID; `name` fields are informational, refreshed at bake time. Run
// `npm run setup-assets` first (it builds the public/ inputs this reads, and
// afterwards copies the baked artifact to public/tides5-data.json for the app).
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve, join } from "node:path";

import { parse } from "smol-toml";

import {
  buildTides4,
  readOverrides,
  readTideAnnotations,
  serializeArtifact,
} from "./bake-tides4.mjs";
import { buildCardMaps, buildDraftRecords } from "./setup-assets.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const ARTIFACT_REL = "data/tides5.jsonc";
const DOC_REL = "docs/cards2/tides5_decklists.md";
const OVERRIDES_REL = "data/tides5-overrides.jsonc";
const KNOWN_GOOD_REL = "docs/known_good_decklists.json";
const ADAPTED_RECORDS_REL = "docs/draft_records_adapted";
const CARDS_TOML_REL = "data/tabula/cards_v2.toml";
const CARDS_JSON_REL = "public/cards_v2-data.json";
const DREAMCALLERS_JSON_REL = "public/dreamcallers-v2-data.json";

// --- Header ------------------------------------------------------------------

const HEADER = `// data/tides5.jsonc — the committed tide decks the \`tides5\` draft-pool variant
// combines into draft pools.
//
// GENERATED FILE. Regenerated by \`npm run bake-tides5\` from the bundled cards,
// Dreamcaller signatures, and the KNOWN-GOOD draft records — the subset of real
// draft seats catalogued in docs/known_good_decklists.json. Do not hand-edit the
// JSON body. The human-readable rendering of the same data is
// docs/cards2/tides5_decklists.md.
//
// \`tides5\` is the SAME algorithm as \`tides4\` (the human-legible counterpart of
// \`sigseed\`), grown from a DIFFERENT corpus: only the known-good decklists feed
// the pick-affinity statistics; every other draft seat is discarded. A draft pool
// is built by combining a few tides — the Dreamcaller's signature tide, plus a
// random subset of its theme (facet) tides, shuffled together and topped up with
// broad tides until there are enough cards, then dealing the first 150 (never more
// than 2 copies of a card). Each facet tide is a single-anchor \`sigseed\` pool, and
// drawing a random subset of them reproduces the variety \`sigseed\` gets from a
// random signature subset.
//
// Cards are keyed by stable cards_v2 UUID; \`name\` fields are informational,
// refreshed at bake time. Each tide may also carry hand-authored identity
// annotations — \`shortName\` (a 1-3 word mechanical label), \`displayName\` (a
// narrative, thematic name) and \`displayDescription\` (a 10-20 word player-facing
// blurb) for the player-facing tide screens, \`summary\` (one sentence),
// \`description\` (one paragraph), and \`color\` (one of the five deck colors:
// purple, green, yellow, blue, orange) — which a re-bake preserves by stable tide
// id.
// \`tidePoolByDreamcaller\` is keyed by Dreamcaller UUID; each
// entry has \`starter\` (the always-joined signature tide, or null), \`facets\` (a
// random subset is drawn each run) and \`neutral\` (the broad tail).
//
// Curated card tweaks (designed combos that the affinity grow scatters, one-off
// add/remove) live in data/tides5-overrides.jsonc and are re-applied on every bake.
//
// To update: edit the known-good list (docs/known_good_decklists.json) or the
// curated tweaks in data/tides5-overrides.jsonc (or let new card/signature changes
// flow in), then:
//   npm run bake-tides5       # rewrites this file + the markdown rendering
//   npm run setup-assets      # copies it to public/tides5-data.json`;

// --- CLI arg helpers ----------------------------------------------------------

function str(argv, flag, fallback) {
  const i = argv.indexOf(flag);
  if (i !== -1 && argv[i + 1] != null) return argv[i + 1];
  const eq = argv.find((a) => a.startsWith(`${flag}=`));
  return eq ? eq.slice(flag.length + 1) : fallback;
}

// --- Inputs -------------------------------------------------------------------

// The set of `"<draftId>#<seat>"` keys naming the known-good decklists. These are
// the only draft seats whose pick records `tides5` learns from.
function loadKnownGoodSeats(rootDir) {
  const path = resolve(rootDir, KNOWN_GOOD_REL);
  if (!existsSync(path)) {
    throw new Error(
      `Missing ${KNOWN_GOOD_REL}. The tides5 bake learns only from the known-good ` +
        `decklists catalogued there.`,
    );
  }
  const parsed = JSON.parse(readFileSync(path, "utf8"));
  const decklists = parsed.decklists ?? [];
  const keys = new Set();
  for (const d of decklists) {
    if (d && d.draftId !== undefined && d.seat !== undefined) {
      keys.add(`${d.draftId}#${d.seat}`);
    }
  }
  return keys;
}

// Read a required JSON bundle from `public/`, with an actionable remedy when the
// `npm run setup-assets` step that builds it has not run.
function readPublicJson(rootDir, rel) {
  const path = resolve(rootDir, rel);
  if (!existsSync(path)) {
    throw new Error(
      `Missing bake input ${rel}. Run \`npm run setup-assets\` first to build the ` +
        `public assets the tides5 bake reads.`,
    );
  }
  return JSON.parse(readFileSync(path, "utf8"));
}

/**
 * Load every tides5 bake input and build the known-good-restricted draft-record
 * corpus. `cards`/`dreamcallers` are the same public bundles `tides4` reads; the
 * draft records are rebuilt from `docs/draft_records_adapted` through the canonical
 * `buildDraftRecords` reader, filtered to the known-good seats and with the
 * exactly-30-picks rule relaxed so non-standard known-good drafts survive. The
 * card maps come from `cards_v2.toml` (the full card universe), exactly as
 * `setup-assets` builds them, so a kept seat's record matches its `tides4` record
 * card-for-card.
 */
function loadTides5Inputs(rootDir, logger = () => {}) {
  const cards = readPublicJson(rootDir, CARDS_JSON_REL);
  const dreamcallers = readPublicJson(rootDir, DREAMCALLERS_JSON_REL);

  const cardsTomlPath = resolve(rootDir, CARDS_TOML_REL);
  if (!existsSync(cardsTomlPath)) {
    throw new Error(`Missing ${CARDS_TOML_REL}.`);
  }
  const cardsV2 = parse(readFileSync(cardsTomlPath, "utf8")).cards;
  const cardMaps = buildCardMaps(cardsV2);

  const seatFilter = loadKnownGoodSeats(rootDir);
  const draftRecords = buildDraftRecords(
    join(rootDir, ADAPTED_RECORDS_REL),
    cardMaps,
    { seatFilter, requireFullPicks: false },
  );

  const present = draftRecords.length;
  logger(
    `Known-good seats: ${seatFilter.size} requested; ${present} found in the draft ` +
      `records (${seatFilter.size - present} not representable as pick records).`,
  );

  // `decklists` is deliberately empty: the pick-affinity corpus the tides5 bake
  // grows from reads only the draft records, and every non-known-good source is
  // discarded.
  return { cards, decklists: [], draftRecords, dreamcallers };
}

// --- Markdown render ----------------------------------------------------------

function renderMarkdown(json, dreamcallers) {
  const tideById = new Map(json.tides.map((t) => [t.id, t]));
  const dcById = new Map(dreamcallers.map((d) => [d.id, d]));
  const lines = [];
  lines.push("# Tides5 decklists");
  lines.push("");
  lines.push(
    "The preconstructed decks (\"tides\") the `?algo=tides5` draft-pool variant",
    "combines into draft pools. `tides5` runs the exact same algorithm as `tides4`",
    "(the human-legible counterpart of `sigseed`), grown from a different corpus: it",
    "learns ONLY from the known-good decklists catalogued in",
    "`docs/known_good_decklists.json`, discarding every other draft seat.",
    "",
    "A pool is built by combining a few tides: the Dreamcaller's signature tide is",
    "always joined, a random subset of its theme (facet) tides is drawn, and broad",
    "tides top the pool up; the combined bag is shuffled and the first 150 cards are",
    "dealt (never more than 2 copies of a card). Each facet tide is a single-anchor",
    "`sigseed` pool, and drawing a random subset of a Dreamcaller's facets reproduces",
    "the variety `sigseed` gets from growing each pool from a random subset of its",
    "signature cards. A signatureless Dreamcaller borrows a random signatured",
    "Dreamcaller's whole pool, so each run leans toward a different coherent archetype.",
    "",
    "GENERATED FILE — regenerated by `npm run bake-tides5` together with",
    "`data/tides5.jsonc` (the machine-readable artifact, keyed by card UUID).",
    "",
  );
  lines.push("## Tide pools by Dreamcaller");
  lines.push("");
  lines.push("| Dreamcaller | Starter | Facets (random subset drawn) | Neutral tail |");
  lines.push("| --- | --- | --- | --- |");
  const nameOfTide = (id) => tideById.get(id)?.name ?? id;
  for (const dc of dreamcallers) {
    const entry = json.tidePoolByDreamcaller[dc.id] ?? {
      starter: null,
      facets: [],
      neutral: [],
    };
    const starter = entry.starter ? nameOfTide(entry.starter) : "(none)";
    const facets =
      entry.facets.length > 4
        ? `${entry.facets.slice(0, 4).map(nameOfTide).join("; ")}; … (${entry.facets.length})`
        : entry.facets.map(nameOfTide).join("; ");
    const neutral =
      entry.neutral.length > 3
        ? `${entry.neutral.length} broad tides`
        : entry.neutral.map(nameOfTide).join("; ");
    lines.push(
      `| ${dc.name} | ${starter} | ${facets || "(none)"} | ${neutral || "(none)"} |`,
    );
  }
  lines.push("");
  for (const tide of json.tides) {
    const copies = tide.cards.reduce((s, c) => s + c.copies, 0);
    const owner = tide.dreamcallerId
      ? dcById.get(tide.dreamcallerId)?.name
      : undefined;
    lines.push(`## ${tide.name}${tide.shortName ? ` — ${tide.shortName}` : ""}`);
    lines.push("");
    lines.push(
      `\`${tide.id}\` — ${tide.role} tide, ${String(tide.cards.length)} distinct cards, ` +
        `${String(copies)} copies` +
        (owner ? `, ${owner}'s signature` : ""),
    );
    lines.push("");
    if (tide.summary) {
      lines.push(`*${tide.summary}*`);
      lines.push("");
    }
    if (tide.description) {
      lines.push(tide.description);
      lines.push("");
    }
    for (const card of tide.cards) {
      lines.push(`- ${String(card.copies)}× ${card.name}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

// --- Reusable build API -------------------------------------------------------
// `run()` (the CLI bake) and `scripts/lib/tides5-check.mjs` (the staleness guard)
// share this so the guard re-bakes through the EXACT generator, never a copy.

/**
 * Produce the serialized `data/tides5.jsonc` text from the current inputs and
 * override layer, carrying the annotations forward from `annotationsSource` (the
 * committed artifact). This is exactly what `run()` writes, so the staleness guard
 * compares the committed file against this.
 */
export function bakeTides5ArtifactText({
  rootDir = ROOT,
  annotationsSource = resolve(rootDir, ARTIFACT_REL),
  logger = () => {},
} = {}) {
  const inputs = loadTides5Inputs(rootDir, logger);
  const overrides = readOverrides(OVERRIDES_REL, rootDir);
  const priorAnnotations = readTideAnnotations(annotationsSource);
  const { json } = buildTides4({ ...inputs, overrides, priorAnnotations, logger });
  return serializeArtifact(json, HEADER);
}

// --- CLI ----------------------------------------------------------------------

function run() {
  const argv = process.argv.slice(2);
  const outRel = str(argv, "--out", ARTIFACT_REL);
  const docRel = str(argv, "--doc", DOC_REL);

  const inputs = loadTides5Inputs(ROOT, (m) => console.log(m));
  const overrides = readOverrides(OVERRIDES_REL, ROOT);
  // Annotations carry forward from the file being rewritten.
  const priorAnnotations = readTideAnnotations(resolve(ROOT, outRel));
  const { json, tides, stats } = buildTides4({
    ...inputs,
    overrides,
    priorAnnotations,
    logger: (m) => console.log(m),
  });

  writeFileSync(resolve(ROOT, outRel), serializeArtifact(json, HEADER));
  writeFileSync(
    resolve(ROOT, docRel),
    renderMarkdown({ ...json, tides }, inputs.dreamcallers) + "\n",
  );

  const meanFacets = stats.sigFacetCounts.length
    ? stats.sigFacetCounts.reduce((s, x) => s + x, 0) / stats.sigFacetCounts.length
    : 0;
  console.log(
    `Tides: ${stats.tideCount} (${stats.sigCount} signature, ${stats.facCount} facet, ${stats.neuCount} neutral).`,
  );
  if (stats.sigFacetCounts.length > 0) {
    console.log(
      `Facets per signatured Dreamcaller: min ${Math.min(...stats.sigFacetCounts)}, ` +
        `mean ${meanFacets.toFixed(1)}, max ${Math.max(...stats.sigFacetCounts)}.`,
    );
  }
  console.log(
    `Coverage: ${stats.distinct} distinct cards across all tides ` +
      `(corpus has ${stats.corpusCards}).`,
  );
  console.log(
    `Tide pools: ${stats.poolCount} of ${inputs.dreamcallers.length} Dreamcallers.`,
  );
  if (stats.noSignal.length > 0) {
    console.warn(
      `Signatured Dreamcallers with no corpus signature: ${stats.noSignal.join(", ")}.`,
    );
  }
  console.log(`Wrote ${outRel} and ${docRel}.`);
}

// Run the bake only when invoked directly (`node scripts/bake-tides5.mjs`), not
// when imported by the staleness guard or its test.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  run();
}
