// Tests for the pure transform in scripts/generate-tango-tokens.mjs, which
// turns a parsed token list (scripts/lib/tango-css-tokens.mjs's
// parseCssTokens output shape) into the generated tokens.ts source text.
// Fixtures are small inline token arrays rather than the real, ever-changing
// contents of src/tango/primitives/tango-tokens.css.
//
// Run with `npx vitest run scripts/generate-tango-tokens.test.mjs`, matching
// every sibling scripts test file (vite.config.ts's `test.include` picks up
// scripts/**/*.test.mjs for `npm test`, so a node:test-only file here would
// make vitest fail with "No test suite found in file").

import { describe, expect, it } from "vitest";
import { buildTokensSource, dedupeLastWins } from "./generate-tango-tokens.mjs";

describe("dedupeLastWins", () => {
  it("keeps the last value for a name declared more than once (last-wins dedupe)", () => {
    const tokens = [
      { name: "text-faint", value: "#111111" },
      { name: "text-faint", value: "#7b7299" },
    ];

    const byName = dedupeLastWins(tokens);

    expect(byName.get("text-faint")).toBe("#7b7299");
    expect(byName.size).toBe(1);
  });

  it("keeps the first-occurrence position when a later duplicate wins on value (stable ordering)", () => {
    const tokens = [
      { name: "a", value: "1" },
      { name: "text-faint", value: "#111111" },
      { name: "b", value: "2" },
      { name: "text-faint", value: "#7b7299" },
    ];

    const byName = dedupeLastWins(tokens);

    expect([...byName.keys()]).toEqual(["a", "text-faint", "b"]);
    expect(byName.get("text-faint")).toBe("#7b7299");
  });
});

describe("buildTokensSource", () => {
  it("emits a generated-file header comment", () => {
    const source = buildTokensSource([{ name: "accent", value: "#8b5cf6" }]);

    expect(source).toMatch(/^\/\/ GENERATED by scripts\/generate-tango-tokens\.mjs/);
    expect(source).toContain("Do\n// not edit by hand");
  });

  it("emits a TOKENS entry per name with both a var() reference and the raw value", () => {
    const source = buildTokensSource([
      { name: "accent", value: "var(--violet-400)" },
      { name: "radius-lg", value: "18px" },
    ]);

    expect(source).toContain(
      '"--accent": { var: "var(--accent)", value: "var(--violet-400)" },',
    );
    expect(source).toContain(
      '"--radius-lg": { var: "var(--radius-lg)", value: "18px" },',
    );
    expect(source).toContain("export const TOKENS = {");
    expect(source).toContain("} as const;");
  });

  it("dedupes a name declared twice in the source, keeping only the last value (last-wins in generated output)", () => {
    const source = buildTokensSource([
      { name: "text-faint", value: "#111111" },
      { name: "text-faint", value: "#7b7299" },
    ]);

    expect(source).toContain(
      '"--text-faint": { var: "var(--text-faint)", value: "#7b7299" },',
    );
    expect(source).not.toContain("#111111");
    // Only one entry for the name — not one line per declaration.
    expect(source.match(/--text-faint/g)).toHaveLength(2); // key + var() reference, once each
  });

  it("escapes a value containing a double quote so the emitted TS stays valid", () => {
    const source = buildTokensSource([
      { name: "quoted", value: 'content: "x"' },
    ]);

    expect(source).toContain('"--quoted": { var: "var(--quoted)", value: "content: \\"x\\"" },');
  });

  it("emits a TokenName union type and a token() helper that looks up the var reference", () => {
    const source = buildTokensSource([{ name: "accent", value: "#8b5cf6" }]);

    expect(source).toContain("export type TokenName = keyof typeof TOKENS;");
    expect(source).toContain("export function token(name: TokenName): string {");
    expect(source).toContain("return TOKENS[name].var;");
  });
});
