// @vitest-environment node

import { mkdtempSync, rmSync, utimesSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it, vi } from "vitest";
import viteConfig, {
  cardEditorSourceWatchPaths,
  gameDataPipelineWatchPatterns,
  generatedDataTomlWatchPattern,
  generatedCardDataDriftPlugin,
  generatedCardArtifactsAreCurrent,
  generatedCardDataWatchPaths,
} from "../vite.config.ts";
import { generatedConfigDataWatchPaths } from "./config-data.mjs";

const rootDir = dirname(
  fileURLToPath(new URL("../package.json", import.meta.url)),
);

function makeHotUpdateContext(file) {
  return {
    file,
    server: {
      ws: {
        send: vi.fn(),
      },
    },
  };
}

function callHotUpdate(plugin, context) {
  const hook = plugin.hotUpdate;

  if (typeof hook === "function") {
    return hook(context);
  }

  return hook?.handler(context);
}

describe("generated card data drift Vite integration", () => {
  it("recognizes editor-generated card artifacts newer than cards.toml", () => {
    const tempRoot = mkdtempSync(join(tmpdir(), "card-artifact-times-"));
    const source = join(tempRoot, "cards.toml");
    const artifact = join(tempRoot, "card-data.json");
    try {
      writeFileSync(source, "source\n");
      writeFileSync(artifact, "[]\n");
      utimesSync(source, 10, 10);
      utimesSync(artifact, 11, 11);
      expect(generatedCardArtifactsAreCurrent(source, [artifact])).toBe(true);

      utimesSync(source, 12, 12);
      expect(generatedCardArtifactsAreCurrent(source, [artifact])).toBe(false);
    } finally {
      rmSync(tempRoot, { recursive: true, force: true });
    }
  });

  it("keeps editor-written card data files out of Vite's reload watcher", () => {
    // Generated TOML files are ignored so editor writes to any card or tag
    // TOML (not just the default cards.toml) never trigger a full
    // page reload. The image-viewer state file is ignored so favorite and used
    // mutations remain in the current editor session. The saved-journeys
    // directory is ignored so saving a journey from the debug overlay does not
    // reload the page. The .worktrees and
    // .claude/worktrees directories are ignored so creating a git worktree
    // (which writes a full repo copy, including a tsconfig.json) does not force
    // a full reload. The canonical tide sources and public Avatar/tides JSON catalogs
    // (all rewritten by the avatar editor) are ignored so those editor saves do
    // not reload the page either. Exploration's canonical templates and generated public catalog
    // are ignored because its API sends a targeted journey reload event. The
    // public dreamwell JSON catalog (rewritten
    // by the Dreamwell editor on every save) is ignored for the same reason. The
    // generated card data paths and the hot-reloadable Dream Atlas catalogs
    // (regenerated by configDataHotReloadPlugin, which sends its own targeted
    // reload event) round out the list.
    expect(viteConfig.server?.watch?.ignored).toEqual([
      generatedDataTomlWatchPattern,
      resolve(join(rootDir, "data", "internal", "image-viewer-state.json")),
      resolve(join(rootDir, "public", "exploration-data.json")),
      resolve(join(rootDir, "saved-journeys")) + "/**",
      resolve(join(rootDir, ".worktrees")) + "/**",
      resolve(join(rootDir, ".claude", "worktrees")) + "/**",
      ...gameDataPipelineWatchPatterns,
      resolve(join(rootDir, "data", "tides.ron")),
      resolve(join(rootDir, "data", "avatars.ron")),
      resolve(join(rootDir, "public", "avatars-v2-data.json")),
      resolve(join(rootDir, "public", "tides4-data.json")),
      resolve(join(rootDir, "public", "dreamwell-data.json")),
      ...cardEditorSourceWatchPaths,
      ...generatedCardDataWatchPaths,
      ...generatedConfigDataWatchPaths({ rootDir }).map((p) => resolve(p)),
    ]);
  });

  it("suppresses full-page reloads for card editor source and generated data writes", () => {
    const plugin = generatedCardDataDriftPlugin();

    expect(
      callHotUpdate(
        plugin,
        makeHotUpdateContext(join(rootDir, "data", "cards.ron")),
      ),
    ).toEqual([]);
    expect(
      callHotUpdate(
        plugin,
        makeHotUpdateContext(
          join(rootDir, "data", "internal", "internal_card_metadata.ron"),
        ),
      ),
    ).toEqual([]);
    expect(
      callHotUpdate(
        plugin,
        makeHotUpdateContext(join(rootDir, "data", "cards.toml")),
      ),
    ).toEqual([]);
    expect(
      callHotUpdate(
        plugin,
        makeHotUpdateContext(join(rootDir, "public", "card-data.json")),
      ),
    ).toEqual([]);
    expect(
      callHotUpdate(
        plugin,
        makeHotUpdateContext(
          join(rootDir, "src", "generated", "config", "card-role-data.json"),
        ),
      ),
    ).toEqual([]);
  });

  it("leaves unrelated file changes to Vite", () => {
    const plugin = generatedCardDataDriftPlugin();

    expect(
      callHotUpdate(
        plugin,
        makeHotUpdateContext(
          join(rootDir, "src", "editor", "CardEditorApp.tsx"),
        ),
      ),
    ).toBeUndefined();
  });
});
