// Generated by scripts/generate-localized-runtime-templates.mjs. Do not edit.
//
// Canonical RON Tx values are static by contract. This module re-authors the
// finite compatibility templates as statically extractable Trox messages so
// runtime adapters can supply arguments without returning plain strings.

import { LocalizedString, tx } from "@trox/runtime";

export type RuntimeTemplateValue = number | boolean | LocalizedString;

// This statically enumerable vocabulary backs subtype names stored as raw
// structural values in the compatibility card catalog.
export function localizedCardSubtype(sourceText: string): LocalizedString | null {
  switch (sourceText) {
    case "Agent":
      return tx("Agent", "[card] Character subtype name.");
    case "Ancient":
      return tx("Ancient", "[card] Character subtype name.");
    case "Child":
      return tx("Child", "[card] Character subtype name.");
    case "Companions":
      return tx("Companions", "[card] Character subtype name.");
    case "Detective":
      return tx("Detective", "[card] Character subtype name.");
    case "Elemental":
      return tx("Elemental", "[card] Character subtype name.");
    case "Emissary":
      return tx("Emissary", "[card] Character subtype name.");
    case "Entity":
      return tx("Entity", "[card] Character subtype name.");
    case "Explorer":
      return tx("Explorer", "[card] Character subtype name.");
    case "Guide":
      return tx("Guide", "[card] Character subtype name.");
    case "Hacker":
      return tx("Hacker", "[card] Character subtype name.");
    case "Mage":
      return tx("Mage", "[card] Character subtype name.");
    case "Monster":
      return tx("Monster", "[card] Character subtype name.");
    case "Musician":
      return tx("Musician", "[card] Character subtype name.");
    case "Noble":
      return tx("Noble", "[card] Character subtype name.");
    case "Outsider":
      return tx("Outsider", "[card] Character subtype name.");
    case "Renegade":
      return tx("Renegade", "[card] Character subtype name.");
    case "Spirit Animal":
      return tx("Spirit Animal", "[card] Character subtype name.");
    case "Squad":
      return tx("Squad", "[card] Character subtype name.");
    case "Super":
      return tx("Super", "[card] Character subtype name.");
    case "Survivor":
      return tx("Survivor", "[card] Character subtype name.");
    case "Synth":
      return tx("Synth", "[card] Character subtype name.");
    case "Thopter":
      return tx("Thopter", "[card] Character subtype name.");
    case "Tinkerer":
      return tx("Tinkerer", "[card] Character subtype name.");
    case "Universal":
      return tx("Universal", "[card] Character subtype name.");
    case "Vehicle":
      return tx("Vehicle", "[card] Character subtype name.");
    case "Visionary":
      return tx("Visionary", "[card] Character subtype name.");
    case "Visitor":
      return tx("Visitor", "[card] Character subtype name.");
    case "Warrior":
      return tx("Warrior", "[card] Character subtype name.");
    case "X":
      return tx("X", "[card] Character subtype name.");
    default:
      return null;
  }
}

// Dream Guide dialogue is nested compatibility data. Enumerating it here keeps
// every authored line statically extractable even when a line is selected at runtime.
export function localizedGuideDialogue(sourceText: string): LocalizedString | null {
  switch (sourceText) {

    default:
      return null;
  }
}

// Dreamsign image descriptions are accessibility copy carried by compatibility
// JSON, so enumerate the finite vocabulary as statically extractable messages.
export function localizedDreamsignImageAlt(sourceText: string): LocalizedString | null {
  switch (sourceText) {
    case "Algae Dreamsign artwork":
      return tx("Algae Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Amanita Dreamsign artwork":
      return tx("Amanita Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Amber Eye Dreamsign artwork":
      return tx("Amber Eye Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Amplified Acorn Dreamsign artwork":
      return tx("Amplified Acorn Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Antler Dreamsign artwork":
      return tx("Antler Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Attuned Petals Dreamsign artwork":
      return tx("Attuned Petals Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Banded Worm Dreamsign artwork":
      return tx("Banded Worm Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Bat Wing Dreamsign artwork":
      return tx("Bat Wing Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Bead Charm Dreamsign artwork":
      return tx("Bead Charm Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Bell Dreamsign artwork":
      return tx("Bell Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Belladonna Dreamsign artwork":
      return tx("Belladonna Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Berries Dreamsign artwork":
      return tx("Berries Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Bestiary Dreamsign artwork":
      return tx("Bestiary Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Bezoar Dreamsign artwork":
      return tx("Bezoar Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Black Attuned Dreamsign artwork":
      return tx("Black Attuned Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Black Cat Dreamsign artwork":
      return tx("Black Cat Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Black Feather Dreamsign artwork":
      return tx("Black Feather Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Black Horn Dreamsign artwork":
      return tx("Black Horn Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Blazing Orb Dreamsign artwork":
      return tx("Blazing Orb Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Blue Crystal Dreamsign artwork":
      return tx("Blue Crystal Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Blue Feather Dreamsign artwork":
      return tx("Blue Feather Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Broomstick Dreamsign artwork":
      return tx("Broomstick Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Brown Acorn Dreamsign artwork":
      return tx("Brown Acorn Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Butterfly Wings Dreamsign artwork":
      return tx("Butterfly Wings Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Cactus Dreamsign artwork":
      return tx("Cactus Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Candle Dreamsign artwork":
      return tx("Candle Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Carved Bone Dreamsign artwork":
      return tx("Carved Bone Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Carved Relic Dreamsign artwork":
      return tx("Carved Relic Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Cauldron Dreamsign artwork":
      return tx("Cauldron Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Charm Bracelet Dreamsign artwork":
      return tx("Charm Bracelet Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Charm Pouch Dreamsign artwork":
      return tx("Charm Pouch Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Charm Staff Dreamsign artwork":
      return tx("Charm Staff Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Clam Shell Dreamsign artwork":
      return tx("Clam Shell Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Cloud Lens Dreamsign artwork":
      return tx("Cloud Lens Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Clover Dreamsign artwork":
      return tx("Clover Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Cracked Mirror Dreamsign artwork":
      return tx("Cracked Mirror Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Cracked Orb Dreamsign artwork":
      return tx("Cracked Orb Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Crow Dreamsign artwork":
      return tx("Crow Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Crystal Orb Dreamsign artwork":
      return tx("Crystal Orb Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Crystal Wand Dreamsign artwork":
      return tx("Crystal Wand Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Curled Tail Dreamsign artwork":
      return tx("Curled Tail Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Curved Blade Dreamsign artwork":
      return tx("Curved Blade Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Dead Rat Dreamsign artwork":
      return tx("Dead Rat Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Dragon Egg Dreamsign artwork":
      return tx("Dragon Egg Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Dreamcatcher Dreamsign artwork":
      return tx("Dreamcatcher Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Egg Nest Dreamsign artwork":
      return tx("Egg Nest Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Essence Vial Dreamsign artwork":
      return tx("Essence Vial Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Eye Amulet Dreamsign artwork":
      return tx("Eye Amulet Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Eye Grimoire Dreamsign artwork":
      return tx("Eye Grimoire Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Eyeball Plant Dreamsign artwork":
      return tx("Eyeball Plant Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Eyeball Slime Dreamsign artwork":
      return tx("Eyeball Slime Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Flaming Button Dreamsign artwork":
      return tx("Flaming Button Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Flash Powder Dreamsign artwork":
      return tx("Flash Powder Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Flower Petals Dreamsign artwork":
      return tx("Flower Petals Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Garlic Bulb Dreamsign artwork":
      return tx("Garlic Bulb Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Gem Codex Dreamsign artwork":
      return tx("Gem Codex Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Ginger Root Dreamsign artwork":
      return tx("Ginger Root Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Glow Pouch Dreamsign artwork":
      return tx("Glow Pouch Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Glowing Crystal Dreamsign artwork":
      return tx("Glowing Crystal Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Gold Feather Dreamsign artwork":
      return tx("Gold Feather Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Gold Key Dreamsign artwork":
      return tx("Gold Key Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Gray Feather Dreamsign artwork":
      return tx("Gray Feather Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Green Amulet Dreamsign artwork":
      return tx("Green Amulet Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Green Beetle Dreamsign artwork":
      return tx("Green Beetle Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Green Cauldron Dreamsign artwork":
      return tx("Green Cauldron Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Green Fly Dreamsign artwork":
      return tx("Green Fly Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Green Slime Dreamsign artwork":
      return tx("Green Slime Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Hair Lock Dreamsign artwork":
      return tx("Hair Lock Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Herb Mortar Dreamsign artwork":
      return tx("Herb Mortar Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Honeycombs Dreamsign artwork":
      return tx("Honeycombs Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Hourglass Dreamsign artwork":
      return tx("Hourglass Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Ice Crystals Dreamsign artwork":
      return tx("Ice Crystals Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Ivory Claw Dreamsign artwork":
      return tx("Ivory Claw Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Larva Dreamsign artwork":
      return tx("Larva Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Leaf Bundle Dreamsign artwork":
      return tx("Leaf Bundle Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Leaf Ledger Dreamsign artwork":
      return tx("Leaf Ledger Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Leather Satchel Dreamsign artwork":
      return tx("Leather Satchel Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Magic Fish Dreamsign artwork":
      return tx("Magic Fish Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Mandrake Root Dreamsign artwork":
      return tx("Mandrake Root Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Mortal Skull Dreamsign artwork":
      return tx("Mortal Skull Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Mushroom Caps Dreamsign artwork":
      return tx("Mushroom Caps Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Notes Dreamsign artwork":
      return tx("Notes Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Oak Leaf Dreamsign artwork":
      return tx("Oak Leaf Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Opal Dreamsign artwork":
      return tx("Opal Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Paired Teeth Dreamsign artwork":
      return tx("Paired Teeth Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Parchment Dreamsign artwork":
      return tx("Parchment Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Pearl Shell Dreamsign artwork":
      return tx("Pearl Shell Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Philosopher's Stone Dreamsign artwork":
      return tx("Philosopher's Stone Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Phoenix Feather Dreamsign artwork":
      return tx("Phoenix Feather Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Pig Nose Dreamsign artwork":
      return tx("Pig Nose Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Piranha Dreamsign artwork":
      return tx("Piranha Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Poison Bottle Dreamsign artwork":
      return tx("Poison Bottle Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Poppy Flower Dreamsign artwork":
      return tx("Poppy Flower Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Potion Mortar Dreamsign artwork":
      return tx("Potion Mortar Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Powder Bowl Dreamsign artwork":
      return tx("Powder Bowl Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Purple Crystal Dreamsign artwork":
      return tx("Purple Crystal Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Purple Potion Dreamsign artwork":
      return tx("Purple Potion Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Pyramid Relic Dreamsign artwork":
      return tx("Pyramid Relic Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Rabbit Tail Dreamsign artwork":
      return tx("Rabbit Tail Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Rainbow Horn Dreamsign artwork":
      return tx("Rainbow Horn Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Rainbow Jellyfish Dreamsign artwork":
      return tx("Rainbow Jellyfish Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Rainbow Mushroom Dreamsign artwork":
      return tx("Rainbow Mushroom Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Raven Skull Dreamsign artwork":
      return tx("Raven Skull Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Red Cheese Dreamsign artwork":
      return tx("Red Cheese Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Red Heart Dreamsign artwork":
      return tx("Red Heart Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Red Pin Dreamsign artwork":
      return tx("Red Pin Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Red Shard Dreamsign artwork":
      return tx("Red Shard Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Root Staff Dreamsign artwork":
      return tx("Root Staff Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Rope Doll Dreamsign artwork":
      return tx("Rope Doll Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Rosemary Dreamsign artwork":
      return tx("Rosemary Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Rune Sack Dreamsign artwork":
      return tx("Rune Sack Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Rune Stone Dreamsign artwork":
      return tx("Rune Stone Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Scorpion Dreamsign artwork":
      return tx("Scorpion Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Sea Tome Dreamsign artwork":
      return tx("Sea Tome Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Sea Urchin Dreamsign artwork":
      return tx("Sea Urchin Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Sealed Letter Dreamsign artwork":
      return tx("Sealed Letter Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Sealed Scroll Dreamsign artwork":
      return tx("Sealed Scroll Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Serpent Tome Dreamsign artwork":
      return tx("Serpent Tome Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Shadow Droplet Dreamsign artwork":
      return tx("Shadow Droplet Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Sickle Dreamsign artwork":
      return tx("Sickle Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Silver Key Dreamsign artwork":
      return tx("Silver Key Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Skull Codex Dreamsign artwork":
      return tx("Skull Codex Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Skull Dagger Dreamsign artwork":
      return tx("Skull Dagger Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Skull Drum Dreamsign artwork":
      return tx("Skull Drum Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Skull Pendant Dreamsign artwork":
      return tx("Skull Pendant Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Slug Dreamsign artwork":
      return tx("Slug Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Spell Tome Dreamsign artwork":
      return tx("Spell Tome Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Spice Blossoms Dreamsign artwork":
      return tx("Spice Blossoms Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Spider Dreamsign artwork":
      return tx("Spider Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Spider Jar Dreamsign artwork":
      return tx("Spider Jar Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Spider Medallion Dreamsign artwork":
      return tx("Spider Medallion Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Spiral Shell Dreamsign artwork":
      return tx("Spiral Shell Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Spotted Egg Dreamsign artwork":
      return tx("Spotted Egg Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Spotted Mug Dreamsign artwork":
      return tx("Spotted Mug Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Star Anise Dreamsign artwork":
      return tx("Star Anise Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Star Badge Dreamsign artwork":
      return tx("Star Badge Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Steel Wand Dreamsign artwork":
      return tx("Steel Wand Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Storm Tome Dreamsign artwork":
      return tx("Storm Tome Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Strange Fruit Dreamsign artwork":
      return tx("Strange Fruit Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Tarot Card Dreamsign artwork":
      return tx("Tarot Card Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Theater Mask Dreamsign artwork":
      return tx("Theater Mask Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Toad Dreamsign artwork":
      return tx("Toad Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Tongue Dreamsign artwork":
      return tx("Tongue Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Tortoise Shell Dreamsign artwork":
      return tx("Tortoise Shell Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Trinket Necklace Dreamsign artwork":
      return tx("Trinket Necklace Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Twisted Herbs Dreamsign artwork":
      return tx("Twisted Herbs Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Voodoo Doll Dreamsign artwork":
      return tx("Voodoo Doll Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "White Rat Dreamsign artwork":
      return tx("White Rat Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Wing Dreamsign artwork":
      return tx("Wing Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Witch Coin Dreamsign artwork":
      return tx("Witch Coin Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Witch Hat Dreamsign artwork":
      return tx("Witch Hat Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Wolf Sigil Dreamsign artwork":
      return tx("Wolf Sigil Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    case "Worm Apple Dreamsign artwork":
      return tx("Worm Apple Dreamsign artwork", "[accessibility] [dreamsign] Dreamsign image description.");
    default:
      return null;
  }
}



export function localizedRuntimeTemplate(
  sourceText: string,
  values: Readonly<Record<string, RuntimeTemplateValue>>,
): LocalizedString | null {
  void values;
  switch (sourceText) {

    default:
      return null;
  }
}
