import { useMemo, useState } from "react";
import type { ReactElement } from "react";
import type { CardData } from "../../types/cards";
import { GlassButton } from "../components/controls/GlassButton";
import { NumberStepper } from "../components/controls/NumberStepper";
import { TextField } from "../components/controls/TextField";
import { GlassDialog } from "../components/overlay/GlassDialog";
import { token } from "../primitives/tokens";

export interface QuestDebugDreamsignView { id: string; name: string; isBane: boolean; }
export interface QuestDebugDeckEntryView { entryId: string; cardId: string; name: string; detail: string; isBane: boolean; }
export interface QuestDebugEditorView { essence: number; essenceCap: number; maxDreamsigns: number; completionLevel: number; dreamsigns: readonly QuestDebugDreamsignView[]; deck: readonly QuestDebugDeckEntryView[]; cards: readonly CardData[]; dreamsignOptions: readonly QuestDebugDreamsignView[]; }
export interface QuestDebugEditorScreenProps { isOpen: boolean; view: QuestDebugEditorView; onClose: () => void; onResourceChange: (id: "essence"|"essenceCap"|"maxDreamsigns"|"completionLevel", delta: number) => void; onAddDreamsign: (id: string) => void; onRemoveDreamsign: (id: string) => void; onToggleDreamsignBane: (id: string) => void; onAddCard: (id: string, bane: boolean) => void; onRemoveCard: (entryId: string) => void; }
const section = { display: "grid", gap: token("--space-4") } as const;
const text = { margin: 0, font: token("--t-body-sm"), color: token("--text-on-glass-muted") } as const;
/** Pure Cumulus operator dialog; mutations stay in its outer controller. */
export function QuestDebugEditorScreen(props: QuestDebugEditorScreenProps): ReactElement | null {
 const [query,setQuery]=useState(""); const matches=useMemo(()=>{const q=query.trim().toLowerCase();return q===""?[]:props.view.cards.filter(c=>c.name.toLowerCase().includes(q)||c.id.toLowerCase().includes(q)).slice(0,50)},[props.view.cards,query]);
 if(!props.isOpen)return null; const step=(id: "essence"|"essenceCap"|"maxDreamsigns"|"completionLevel",value:number,label:string)=><NumberStepper label={label} value={value} decrementLabel={`Decrease ${label}`} incrementLabel={`Increase ${label}`} onDecrement={()=>props.onResourceChange(id,-1)} onIncrement={()=>props.onResourceChange(id,1)} placement="onGlass" testId={`quest-debug-${id}`} />;
 return <div className="cumulus" style={{minHeight:"100vh"}} data-quest-debug-editor=""><GlassDialog title="Edit Quest State" subtitle="Make explicit diagnostic changes to the active run." onClose={props.onClose} fullScreen><div style={{display:"grid",gap:token("--space-7")}}><section style={section}><h3 style={{margin:0,font:token("--t-title-sm"),color:token("--text-on-glass")}}>Resources</h3>{step("essence",props.view.essence,"Essence")}{step("essenceCap",props.view.essenceCap,"Essence cap")}{step("maxDreamsigns",props.view.maxDreamsigns,"Max dreamsigns")}{step("completionLevel",props.view.completionLevel,"Completion level")}</section><section style={section}><h3 style={{margin:0,font:token("--t-title-sm"),color:token("--text-on-glass")}}>Dreamsigns</h3>{props.view.dreamsigns.map(s=><div key={s.id} style={section}><p style={text}>{s.name}{s.isBane?" · bane":""}</p><div style={{display:"flex",gap:token("--space-3")}}><GlassButton label={s.isBane?"Unbane":"Bane"} onPress={()=>props.onToggleDreamsignBane(s.id)} placement="onGlass"/><GlassButton label="Remove" onPress={()=>props.onRemoveDreamsign(s.id)} placement="onGlass" variant="danger"/></div></div>)}</section><section style={section}><TextField label="Add card" value={query} onChange={setQuery} kind="search" placeholder="Search by name or UUID"/>{matches.map(c=><div key={c.id} style={section}><p style={text}>{c.name} · {c.id}</p><div style={{display:"flex",gap:token("--space-3")}}><GlassButton label="Add" onPress={()=>props.onAddCard(c.id,false)} placement="onGlass"/><GlassButton label="Add as bane" onPress={()=>props.onAddCard(c.id,true)} placement="onGlass" variant="danger"/></div></div>)}</section><section style={section}><h3 style={{margin:0,font:token("--t-title-sm"),color:token("--text-on-glass")}}>Deck</h3>{props.view.deck.map(e=><div key={e.entryId} style={section}><p style={text}>{e.name} · {e.detail}{e.isBane?" · bane":""}</p><GlassButton label="Remove" onPress={()=>props.onRemoveCard(e.entryId)} placement="onGlass" variant="danger"/></div>)}</section></div></GlassDialog></div>;
}
