import { describe, it, expect, vi, beforeEach } from "vitest";
import { cardImageUrl, loadCardDatabase } from "./card-database";
import type { CardData } from "../types/cards";

const SAMPLE_CARD: CardData = {
  name: "Test Card",
  id: "abc-123",
  cardNumber: 42,
  cardType: "Character",
  subtype: "Beast",
  isStarter: false,
  energyCost: 3,
  spark: 2,
  isFast: false,
  tides: ["tide_alpha"],
  renderedText: "Sample text",
  imageNumber: 12345,
  artOwned: true,
};

beforeEach(() => {
  vi.restoreAllMocks();
});

describe("loadCardDatabase", () => {
  it("fetches card-data.json and returns a Map keyed by cardNumber", async () => {
    const cards: CardData[] = [
      SAMPLE_CARD,
      { ...SAMPLE_CARD, cardNumber: 99, name: "Another Card" },
    ];
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve(cards),
      }),
    );
    const db = await loadCardDatabase();
    expect(db.size).toBe(2);
    expect(db.get(42)?.name).toBe("Test Card");
    expect(db.get(99)?.name).toBe("Another Card");
  });

  it("throws on non-ok response", async () => {
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue({
        ok: false,
        status: 404,
        statusText: "Not Found",
      }),
    );
    await expect(loadCardDatabase()).rejects.toThrow("Failed to load card data");
  });
});

describe("cardImageUrl", () => {
  it("returns the webp path for a given card number", () => {
    expect(cardImageUrl(42)).toBe("/cards/42.webp");
  });

  it("works for card number 1", () => {
    expect(cardImageUrl(1)).toBe("/cards/1.webp");
  });

  it("works for large card numbers", () => {
    expect(cardImageUrl(503)).toBe("/cards/503.webp");
  });
});

/**
 * Integration test: loads the real card-data.json (generated by setup-assets)
 * and verifies the loader produces a correct database from actual card data.
 * Uses dynamic imports for Node.js fs/path to avoid browser tsconfig errors.
 */
async function readCardDataJson(): Promise<CardData[] | null> {
  try {
    const fs = await import("node:fs");
    const url = await import("node:url");
    const path = await import("node:path");
    const dir = path.dirname(url.fileURLToPath(import.meta.url));
    const jsonPath = path.resolve(dir, "../../public/card-data.json");
    if (!fs.existsSync(jsonPath)) return null;
    return JSON.parse(fs.readFileSync(jsonPath, "utf8")) as CardData[];
  } catch {
    return null;
  }
}
describe("loadCardDatabase integration (real card-data.json)", () => {
  it("loads the generated card set and indexes it by cardNumber", async () => {
    const raw = await readCardDataJson();
    if (raw === null) return;

    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve(raw),
      }),
    );

    const db = await loadCardDatabase();
    expect(db.size).toBe(592);
  });

  it("every card has all required fields with correct types", async () => {
    const raw = await readCardDataJson();
    if (raw === null) return;

    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve(raw),
      }),
    );

    const db = await loadCardDatabase();
    const validCardTypes = new Set(["Character", "Event"]);
    for (const [cardNumber, card] of db) {
      expect(cardNumber).toBe(card.cardNumber);
      expect(typeof card.name).toBe("string");
      expect(typeof card.id).toBe("string");
      expect(typeof card.cardNumber).toBe("number");
      expect(validCardTypes.has(card.cardType)).toBe(true);
      expect(typeof card.subtype).toBe("string");
      expect(typeof card.isStarter).toBe("boolean");
      expect(
        card.energyCost === null || typeof card.energyCost === "number",
      ).toBe(true);
      expect(
        card.spark === null || typeof card.spark === "number",
      ).toBe(true);
      expect(typeof card.isFast).toBe("boolean");
      expect(Array.isArray(card.tides)).toBe(true);
      expect(card.tides.length).toBeGreaterThan(0);
      for (const packageTideId of card.tides) {
        expect(typeof packageTideId).toBe("string");
        expect(packageTideId.length).toBeGreaterThan(0);
      }
      expect(typeof card.renderedText).toBe("string");
      expect(typeof card.imageNumber).toBe("number");
      expect(typeof card.artOwned).toBe("boolean");
      // Rarity is sourced from the TOML and propagates through setup-assets.
      // Most cards have no rarity; only the Legendary and Starter buckets
      // exist.
      const validRarities = new Set(["Legendary", "Starter"]);
      if (card.rarity !== undefined) {
        expect(validRarities.has(card.rarity)).toBe(true);
      }
    }
  });

  it("contains at least one Legendary card to drive the legendary frame", async () => {
    const raw = await readCardDataJson();
    if (raw === null) return;

    const legendaries = raw.filter((card) => card.rarity === "Legendary");
    expect(legendaries.length).toBeGreaterThan(0);
  });

  it("sample card lookup returns expected structure", async () => {
    const raw = await readCardDataJson();
    if (raw === null) return;

    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve(raw),
      }),
    );

    const db = await loadCardDatabase();
    const card = db.get(1);
    expect(card).toBeDefined();
    expect(card?.cardNumber).toBe(1);
    expect(card?.name.length).toBeGreaterThan(0);
    expect(card?.tides.length).toBeGreaterThan(0);
  });
});
