import { describe, it, expect, vi, beforeEach } from "vitest";
import {
  cardAccentTide,
  cardImageUrl,
  tideIconUrl,
  loadCardDatabase,
  NAMED_TIDES,
  TIDE_COLORS,
} from "./card-database";
import type { Tide, CardData } from "../types/cards";

const SAMPLE_CARD: CardData = {
  name: "Test Card",
  id: "abc-123",
  cardNumber: 42,
  cardType: "Character",
  subtype: "Beast",
  isStarter: false,
  energyCost: 3,
  spark: 2,
  isFast: false,
  tides: ["Bloom"],
  renderedText: "Sample text",
  imageNumber: 12345,
  artOwned: true,
};

beforeEach(() => {
  vi.restoreAllMocks();
});

describe("loadCardDatabase", () => {
  it("fetches card-data.json and returns a Map keyed by cardNumber", async () => {
    const cards: CardData[] = [
      SAMPLE_CARD,
      { ...SAMPLE_CARD, cardNumber: 99, name: "Another Card" },
    ];
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve(cards),
      }),
    );
    const db = await loadCardDatabase();
    expect(db.size).toBe(2);
    expect(db.get(42)?.name).toBe("Test Card");
    expect(db.get(99)?.name).toBe("Another Card");
  });

  it("throws on non-ok response", async () => {
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue({
        ok: false,
        status: 404,
        statusText: "Not Found",
      }),
    );
    await expect(loadCardDatabase()).rejects.toThrow("Failed to load card data");
  });
});

describe("cardImageUrl", () => {
  it("returns the webp path for a given card number", () => {
    expect(cardImageUrl(42)).toBe("/cards/42.webp");
  });

  it("works for card number 1", () => {
    expect(cardImageUrl(1)).toBe("/cards/1.webp");
  });

  it("works for large card numbers", () => {
    expect(cardImageUrl(503)).toBe("/cards/503.webp");
  });
});

describe("tideIconUrl", () => {
  it("returns the png path for a named tide", () => {
    expect(tideIconUrl("Bloom")).toBe("/tides/Bloom.png");
  });

  it("returns png paths for all named tides", () => {
    const named: Tide[] = [
      "Bloom",
      "Arc",
      "Ignite",
      "Pact",
      "Umbra",
      "Rime",
      "Surge",
    ];
    for (const tide of named) {
      expect(tideIconUrl(tide)).toBe(`/tides/${tide}.png`);
    }
  });

  it("returns a fallback for Neutral tide", () => {
    const url = tideIconUrl("Neutral");
    expect(url).not.toBe("/tides/Neutral.png");
    expect(url.length).toBeGreaterThan(0);
    expect(url).toContain("data:");
  });
});

describe("NAMED_TIDES", () => {
  it("contains exactly 7 tides excluding Neutral", () => {
    expect(NAMED_TIDES).toHaveLength(7);
    expect(NAMED_TIDES).not.toContain("Neutral");
  });

  it("contains all named tide values", () => {
    expect(NAMED_TIDES).toContain("Bloom");
    expect(NAMED_TIDES).toContain("Arc");
    expect(NAMED_TIDES).toContain("Ignite");
    expect(NAMED_TIDES).toContain("Pact");
    expect(NAMED_TIDES).toContain("Umbra");
    expect(NAMED_TIDES).toContain("Rime");
    expect(NAMED_TIDES).toContain("Surge");
  });
});

describe("TIDE_COLORS", () => {
  it("maps all 8 tides to hex colors", () => {
    const expected: Record<Tide, string> = {
      Bloom: "#10b981",
      Arc: "#f59e0b",
      Ignite: "#ef4444",
      Pact: "#ec4899",
      Umbra: "#8b5cf6",
      Rime: "#3b82f6",
      Surge: "#06b6d4",
      Neutral: "#9ca3af",
    };
    for (const [tide, color] of Object.entries(expected)) {
      expect(TIDE_COLORS[tide as Tide]).toBe(color);
    }
  });
});

/**
 * Integration test: loads the real card-data.json (generated by setup-assets)
 * and verifies the loader produces a correct database from actual card data.
 * Uses dynamic imports for Node.js fs/path to avoid browser tsconfig errors.
 */
/* eslint-disable @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-argument */
async function readCardDataJson(): Promise<CardData[] | null> {
  try {
    // @ts-expect-error -- Node.js modules available at runtime in Vitest
    const fs = await import("node:fs");
    // @ts-expect-error -- Node.js modules available at runtime in Vitest
    const url = await import("node:url");
    // @ts-expect-error -- Node.js modules available at runtime in Vitest
    const path = await import("node:path");
    const dir = path.dirname(url.fileURLToPath(import.meta.url));
    const jsonPath = path.resolve(dir, "../../public/card-data.json");
    if (!fs.existsSync(jsonPath)) return null;
    return JSON.parse(fs.readFileSync(jsonPath, "utf8")) as CardData[];
  } catch {
    return null;
  }
}
/* eslint-enable @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-argument */

describe("loadCardDatabase integration (real card-data.json)", () => {
  it("loads the generated card set and indexes it by cardNumber", async () => {
    const raw = await readCardDataJson();
    if (raw === null) return;

    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve(raw),
      }),
    );

    const db = await loadCardDatabase();
    expect(db.size).toBe(592);
  });

  it("every card has all required fields with correct types", async () => {
    const raw = await readCardDataJson();
    if (raw === null) return;

    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve(raw),
      }),
    );

    const db = await loadCardDatabase();
    const validCardTypes = new Set(["Character", "Event"]);
    for (const [cardNumber, card] of db) {
      expect(cardNumber).toBe(card.cardNumber);
      expect(typeof card.name).toBe("string");
      expect(typeof card.id).toBe("string");
      expect(typeof card.cardNumber).toBe("number");
      expect(validCardTypes.has(card.cardType)).toBe(true);
      expect(typeof card.subtype).toBe("string");
      expect(typeof card.isStarter).toBe("boolean");
      expect(
        card.energyCost === null || typeof card.energyCost === "number",
      ).toBe(true);
      expect(
        card.spark === null || typeof card.spark === "number",
      ).toBe(true);
      expect(typeof card.isFast).toBe("boolean");
      expect(Array.isArray(card.tides)).toBe(true);
      expect(card.tides.length).toBeGreaterThan(0);
      for (const packageTideId of card.tides) {
        expect(typeof packageTideId).toBe("string");
        expect(packageTideId.length).toBeGreaterThan(0);
      }
      expect(typeof card.renderedText).toBe("string");
      expect(typeof card.imageNumber).toBe("number");
      expect(typeof card.artOwned).toBe("boolean");
    }
  });

  it("sample card lookup returns expected structure", async () => {
    const raw = await readCardDataJson();
    if (raw === null) return;

    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve(raw),
      }),
    );

    const db = await loadCardDatabase();
    const card = db.get(1);
    expect(card).toBeDefined();
    expect(card?.cardNumber).toBe(1);
    expect(card?.name.length).toBeGreaterThan(0);
    expect(card ? cardAccentTide(card) : null).not.toBeNull();
  });
});
