const DREAMSIGN_SIGNATURES_JSON_PATH = "/dreamsign-signatures-data.json";

export interface DreamsignSignature {
  id: string; // dreamsign UUID
  category: "neutral" | "tailored";
  signatureCardIds: string[]; // lowercased cards_v2 UUIDs ([] for neutral)
}

interface RawDreamsignSignature {
  id: string;
  category: string;
  signatureCardIds?: string[];
}

/**
 * Fetches the dreamsign signature classification from the asset pipeline output
 * (`public/dreamsign-signatures-data.json`, generated by
 * `scripts/setup-assets.mjs` from `data/dreamsign_signatures.toml`).
 *
 * Returns a Map keyed by dreamsign UUID (lowercased). A dreamsign whose UUID is
 * absent from the map is treated as neutral by callers.
 *
 * @throws When the HTTP fetch fails or a signature entry has a category value
 *   outside the valid set `"neutral" | "tailored"`.
 */
export async function loadDreamsignSignatures(): Promise<
  ReadonlyMap<string, DreamsignSignature>
> {
  const response = await fetch(DREAMSIGN_SIGNATURES_JSON_PATH);
  if (!response.ok) {
    throw new Error(
      `Failed to load dreamsign signatures: ${String(response.status)} ${response.statusText}`,
    );
  }
  const raw = (await response.json()) as RawDreamsignSignature[];

  const signatures = new Map<string, DreamsignSignature>();
  for (const entry of raw) {
    const id = entry.id.toLowerCase();
    const category = entry.category;
    if (category !== "neutral" && category !== "tailored") {
      throw new Error(
        `Invalid category "${String(category)}" on dreamsign signature ${id} — must be "neutral" or "tailored"`,
      );
    }
    const signatureCardIds = (entry.signatureCardIds ?? []).map((cid) =>
      cid.toLowerCase(),
    );
    signatures.set(id, {
      id,
      category,
      signatureCardIds,
    });
  }
  return signatures;
}
