const DREAMSIGN_PROFILES_JSON_PATH = "/dreamsign-profiles-data.json";

export interface DreamsignProfile {
  id: string; // dreamsign UUID
  subtypes: readonly string[];
  cardTypes: readonly string[];
  costBands: readonly ("cheap" | "mid" | "big")[];
  keywords: readonly string[];
  quality: 1 | 2 | 3;
}

interface RawDreamsignProfile {
  id: string;
  subtypes?: string[];
  cardTypes?: string[];
  costBands?: string[];
  keywords?: string[];
  quality: number;
}

/**
 * Fetches the curated dreamsign profiles from the asset pipeline output
 * (`public/dreamsign-profiles-data.json`, generated by
 * `scripts/setup-assets.mjs` from `data/tabula/dreamsign_profiles.toml`).
 *
 * Returns a Map keyed by dreamsign UUID.  A dreamsign whose UUID is absent
 * from the map has no profile and is treated downstream as featureless
 * quality 2.
 *
 * @throws When the HTTP fetch fails or a profile has a quality value outside
 *   the valid range 1–3 (which would silently produce NaN scores at runtime).
 */
export async function loadDreamsignProfiles(): Promise<
  ReadonlyMap<string, DreamsignProfile>
> {
  const response = await fetch(DREAMSIGN_PROFILES_JSON_PATH);
  if (!response.ok) {
    throw new Error(
      `Failed to load dreamsign profiles: ${String(response.status)} ${response.statusText}`,
    );
  }
  const raw = (await response.json()) as RawDreamsignProfile[];

  const profiles = new Map<string, DreamsignProfile>();
  for (const entry of raw) {
    const q = entry.quality;
    if (q !== 1 && q !== 2 && q !== 3) {
      throw new Error(
        `Invalid quality ${String(q)} on dreamsign profile ${entry.id} — must be 1, 2, or 3`,
      );
    }
    profiles.set(entry.id, {
      id: entry.id,
      subtypes: entry.subtypes ?? [],
      cardTypes: entry.cardTypes ?? [],
      costBands: (entry.costBands ?? []) as ("cheap" | "mid" | "big")[],
      keywords: entry.keywords ?? [],
      quality: q,
    });
  }
  return profiles;
}
