// Generated by scripts/generate-localization-types.mjs. Do not edit.
import type { FluentVariable } from "@fluent/bundle";

export const FLUENT_MESSAGE_IDS = [
  "journey-complete-title",
  "journey-complete-new-journey",
  "journey-complete-stat-battles",
  "journey-complete-stat-dreamscapes",
  "journey-complete-stat-cards",
  "journey-complete-stat-dreamsigns",
  "journey-complete-stat-essence",
] as const;

export interface FluentMessageArgumentsById {
  readonly "journey-complete-title": never;
  readonly "journey-complete-new-journey": never;
  readonly "journey-complete-stat-battles": { readonly count: FluentVariable };
  readonly "journey-complete-stat-dreamscapes": {
    readonly count: FluentVariable;
  };
  readonly "journey-complete-stat-cards": never;
  readonly "journey-complete-stat-dreamsigns": {
    readonly count: FluentVariable;
  };
  readonly "journey-complete-stat-essence": never;
}

export type FluentMessageId = (typeof FLUENT_MESSAGE_IDS)[number];

/** Arguments accepted by a message. Messages that need variables require them. */
export type FluentMessageArguments<Id extends FluentMessageId> =
  Id extends FluentMessageId
    ? FluentMessageArgumentsById[Id] extends never
      ? [variables?: Readonly<Record<string, FluentVariable>>]
      : [variables: FluentMessageArgumentsById[Id]]
    : never;
