const MERCHANT_CORPUS_JSON_PATH = "/merchant-corpus-data.json";

export interface MerchantCorpusCard {
  quality: number; // [0,1] normalized
  multiplicity: number; // [0,1]
  df: number;
  cluster?: number;
}

export interface MerchantCluster {
  id: number;
  flagship: string; // card UUID
  members: readonly string[];
}

export interface MerchantCorpus {
  cards: ReadonlyMap<string, MerchantCorpusCard>;
  clusters: readonly MerchantCluster[];
}

interface RawMerchantCorpusCard {
  quality: number;
  multiplicity: number;
  df: number;
  cluster?: number;
}

interface RawMerchantCorpus {
  version: number;
  source: string;
  cards: Record<string, RawMerchantCorpusCard>;
  clusters: Array<{ id: number; flagship: string; members: string[] }>;
}

/**
 * Fetches the baked merchant corpus artifact from the asset pipeline output
 * (`public/merchant-corpus-data.json`, generated by `scripts/setup-assets.mjs`
 * from `data/merchant_corpus.json`).
 *
 * Cards absent from the returned corpus have no signal — callers treat them as
 * unclustered with quality 0 and multiplicity 0.
 */
export async function loadMerchantCorpus(): Promise<MerchantCorpus> {
  const response = await fetch(MERCHANT_CORPUS_JSON_PATH);
  if (!response.ok) {
    throw new Error(
      `Failed to load merchant corpus: ${String(response.status)} ${response.statusText}`,
    );
  }
  const raw = (await response.json()) as RawMerchantCorpus;

  const cards = new Map<string, MerchantCorpusCard>();
  for (const [uuid, entry] of Object.entries(raw.cards)) {
    const card: MerchantCorpusCard = {
      quality: entry.quality,
      multiplicity: entry.multiplicity,
      df: entry.df,
    };
    if (entry.cluster !== undefined) {
      card.cluster = entry.cluster;
    }
    cards.set(uuid, card);
  }

  const clusters: MerchantCluster[] = raw.clusters.map((c) => ({
    id: c.id,
    flagship: c.flagship,
    members: c.members,
  }));

  return { cards, clusters };
}
